import Timer from './../components/Timer';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Center, Container } from '@mantine/core';
import Navbar from '../components/Navbar';
import create from 'zustand';

interface TimerState {
	time: Map<string, { value: number }>;
	changeTime: (type: string, value: number) => void;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const useTimerStore = create<TimerState>()((set, get) => ({
	time: new Map([
		['pomodoro', { value: 25 }],
		['short', { value: 5 }],
		['long', { value: 25 }],
	]),
	changeTime: (type, value) => {
		const time = get().time;
		time.delete(type);
		set(() => timeToChangevalue);
	},
}));

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Center>
				<Container size='md' px='sm'>
					<Navbar />
					<Timer />
				</Container>
			</Center>
		</>
	);
};

export default Home;
