import type { NextPage } from 'next';
import Head from 'next/head';
import {
	Center,
	Container,
	Paper,
	PaperProps,
	Title,
	Stack,
	Button,
} from '@mantine/core';
import Navbar from '../components/Navbar';
import { PlayIcon } from '@heroicons/react/24/solid';

const Home: NextPage = (props: PaperProps) => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Center>
				<Container size='md' px='sm'>
					<Navbar />
					<Paper radius='sm' p='xl' shadow='xs' withBorder {...props}>
						<Stack align='center'>
							<Title
								order={1}
								sx={{
									fontSize: '4rem',
								}}>
								25:00
							</Title>
							<Button size='xl' rightIcon={<PlayIcon width={24} />}>
								START
							</Button>
						</Stack>
					</Paper>
				</Container>
			</Center>
		</>
	);
};

export default Home;
